name: publish

on:
  push:
    tags: "v*.*.*"

jobs:
  publish:
    strategy:
      matrix:
        registry:
          - name: github
            url: https://registry.npmjs.org
            token_secret: NPM_TOKEN
          - name: npm
            url: https://npm.pkg.github.com
            token_secret: GITHUB_NPM_TOKEN
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets[matrix.registry.token_secret] }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: ">=21.0.0"
          cache: pnpm
          registry-url: ${{ matrix.registry.url }}
      - name: Build & Publish
        run: |
          pnpm install --frozen-lockfile
          pnpm publish --access public --no-git-checks
